apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gdp-prediction-app.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "gdp-prediction-app.name" . }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}
