replicaCount: 2

env:
  APP_ENV: "staging"

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6

ingress:
  hosts:
    - host: gdp-staging.api.domain.com
      paths:
        - path: /
          pathType: Prefix
