replicaCount: 2

env:
  APP_ENV: "dev"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

ingress:
  hosts:
    - host: gdp-dev.api.domain.com
      paths:
        - path: /
          pathType: Prefix
