apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gdp-prediction-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/someshtarra/TERRAFORM.git'
    targetRevision: HEAD
    path: gitops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
